version: '3'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    #command: tail -f /dev/null
    environment:
      - TERM=xterm-256color
    ports:
      - "8080:8080"
    volumes:
      - .:/home/docker/application
      